[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"
style  = "Regular"

[window]
# hide the title bar
decorations = "none"
opacity     = 0.92

[scrolling]
history    = 10_000      # lines kept in scrollback
multiplier = 3           # integer u8, not a float

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard     = true
semantic_escape_chars = "││:\"' ()[]{}<>"

[cursor]
blink_interval = 800     # ms between blinks
blink_timeout  = 0       # 0 = never stop
thickness      = 0.15    # relative to cell width

[cursor.style]
shape    = "Beam"        # Block | Underline | Beam
blinking = "Always"      # Never | Off | On | Always

[terminal.shell]
program = "/usr/bin/zsh"
args    = ["-l"]

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[colors.normal]
black   = "#3B4252"
blue    = "#81A1C1"
cyan    = "#88C0D0"
green   = "#A3BE8C"
magenta = "#B48EAD"
red     = "#BF616A"
white   = "#E5E9F0"
yellow  = "#EBCB8B"

[colors.bright]
black   = "#4C566A"
blue    = "#81A1C1"
cyan    = "#8FBCBB"
green   = "#A3BE8C"
magenta = "#B48EAD"
red     = "#BF616A"
white   = "#ECEFF4"
yellow  = "#EBCB8B"